id: P009628
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-19 20:41:43.742874
source_metadata:
  id: bdr:W2625
  title: སྐལ་བཟང་རྒྱ་མཚོའི་རྣམ་ཐར
  author: ''
  volumes:
    df7be5c0a8eb4dd48d979a63f68c2994:
      image_group_id: I1PD36292
      title: ''
      volume_number: 1
      total_pages: 626
      base_file: v001.txt
    a974da92cfac49b49e74b1f55112c06b:
      image_group_id: I1PD36293
      title: ''
      volume_number: 2
      total_pages: 534
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
